import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="w-full m-auto flex min-h-screen">
				<main className="flex flex-1">{children}</main>
			</body>
		</html>
	)
}
