import { ThemeProvider } from '@/components/providers/theme-provider'
import { cn } from '@/lib/utils'
import { Inter } from 'next/font/google'
import { Toaster } from 'react-hot-toast'
import './globals.css'

const font = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Incognito.cash',
	description: 'Generated by Ecoterreans',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body className={cn(font.className, '')}>
				<ThemeProvider attribute="class" defaultTheme="dark" enableSystem={false} storageKey="contribuere-theme">
					<Toaster />
					{children}
				</ThemeProvider>
			</body>
		</html>
	)
}
