export const metadata = {
	title: 'Incognito.cash',
	description: 'Generated by Ecoterreans',
}

export default async function MainLayout({ children }: { children: React.ReactNode }) {
	return <main>{children}</main>
}
