export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function MainLayout({ children }: { children: React.ReactNode }) {
	return (
		<div className="h-full">
			<main className="h-full">{children}</main>
		</div>
	)
}
